import { ProjectDocument } from '../domain/project/types';
import { CURRENT_SCHEMA_VERSION } from '../domain/project/document';

export const SAMPLE_PROJECTS: ProjectDocument[] = [
  // --- PROJECT 1 (DỄ): ĐÈN NGỦ TỰ ĐỘNG ---
  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'sample-auto-nightlight',
    name: 'Đèn ngủ tự động',
    description: 'Minh họa cảm biến ánh sáng LDR điều khiển transistor NPN bật tắt LED vàng tự động khi trời tối.',
    revision: 1,
    units: 'mm',
    board: {
      width: 70,
      depth: 70,
      thickness: 1.6,
      solderMaskColor: '#14532d', // Forest Green
      copperLayerCount: 2,
      gridSpacing: 2.54,
      shape: 'square',
    },
    metadata: {
      difficulty: 'Dễ',
      category: 'Cảm biến quang & Bán dẫn',
      slug: 'den-ngu-tu-dong',
      version: '1.0.0',
      isTemplate: true,
      learningObjectives: [
        'Nguyên lý hoạt động của quang trở LDR theo cường độ ánh sáng',
        'Ứng dụng Transistor NPN đóng ngắt dòng qua tải LED',
        'Điều chỉnh độ nhạy sáng thông qua biến trở xoay Potentiometer',
      ],
      requiredComponents: [
        'dc-source',
        'ldr',
        'resistor',
        'potentiometer',
        'transistor-npn',
        'led',
        'connector',
      ],
      simulationSupport: true,
    },
    components: [
      {
        instanceId: 'pwr-main',
        definitionId: 'dc-source',
        name: 'Nguồn 5V',
        position: { x: -22, y: 0, z: -18 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 5.0 },
      },
      {
        instanceId: 'term-ext',
        definitionId: 'connector',
        name: 'Terminal Đấu dây',
        position: { x: -22, y: 0, z: 18 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: {},
      },
      {
        instanceId: 'ldr-sense',
        definitionId: 'ldr',
        name: 'Quang trở LDR',
        position: { x: -4, y: 0, z: -15 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { lightLevelPercent: 30 },
      },
      {
        instanceId: 'pot-sens',
        definitionId: 'potentiometer',
        name: 'Chiết áp 10k',
        position: { x: -4, y: 0, z: 15 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { maxResistance: 10000 },
      },
      {
        instanceId: 'q-switch',
        definitionId: 'transistor-npn',
        name: 'NPN 2N2222',
        position: { x: 12, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: {},
      },
      {
        instanceId: 'res-limit',
        definitionId: 'resistor',
        name: 'R1 220Ω',
        position: { x: 22, y: 0, z: -18 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { resistance: 220 },
      },
      {
        instanceId: 'led-lamp',
        definitionId: 'led',
        name: 'LED Vàng',
        position: { x: 22, y: 0, z: 12 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { color: 'yellow' },
      },
    ],
    connections: [
      {
        id: 'c1-vcc-ldr',
        fromComponentId: 'pwr-main',
        fromPinId: 'vcc',
        toComponentId: 'ldr-sense',
        toPinId: 'pin1',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c2-ldr-base',
        fromComponentId: 'ldr-sense',
        fromPinId: 'pin2',
        toComponentId: 'q-switch',
        toPinId: 'base',
        wireColor: '#f59e0b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c3-base-pot',
        fromComponentId: 'q-switch',
        fromPinId: 'base',
        toComponentId: 'pot-sens',
        toPinId: 'wiper',
        wireColor: '#eab308',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c4-pot-gnd',
        fromComponentId: 'pot-sens',
        fromPinId: 'pin2',
        toComponentId: 'pwr-main',
        toPinId: 'gnd',
        wireColor: '#1e293b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c5-vcc-res',
        fromComponentId: 'pwr-main',
        fromPinId: 'vcc',
        toComponentId: 'res-limit',
        toPinId: 'pin1',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c6-res-led',
        fromComponentId: 'res-limit',
        fromPinId: 'pin2',
        toComponentId: 'led-lamp',
        toPinId: 'anode',
        wireColor: '#f59e0b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c7-led-collector',
        fromComponentId: 'led-lamp',
        fromPinId: 'cathode',
        toComponentId: 'q-switch',
        toPinId: 'collector',
        wireColor: '#06b6d4',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c8-emitter-gnd',
        fromComponentId: 'q-switch',
        fromPinId: 'emitter',
        toComponentId: 'pwr-main',
        toPinId: 'gnd',
        wireColor: '#1e293b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c9-term-vcc',
        fromComponentId: 'term-ext',
        fromPinId: 'pin1',
        toComponentId: 'pwr-main',
        toPinId: 'vcc',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c10-term-gnd',
        fromComponentId: 'term-ext',
        fromPinId: 'pin2',
        toComponentId: 'pwr-main',
        toPinId: 'gnd',
        wireColor: '#1e293b',
        wireStyle: 'orthogonal',
      },
    ],
    wireRoutes: [],
    createdAt: '2026-09-14T00:00:00.000Z',
    updatedAt: '2026-09-14T00:00:00.000Z',
  },

  // --- PROJECT 2 (TRUNG BÌNH): ĐÈN NHÁY ĐIỀU CHỈNH TỐC ĐỘ ---
  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'sample-speed-blinker',
    name: 'Đèn nháy điều chỉnh tốc độ',
    description: 'Mạch dao động đa hài NE555 Astable kết hợp chiết áp biến trở điều chỉnh tần số chớp LED xanh dương.',
    revision: 1,
    units: 'mm',
    board: {
      width: 95,
      depth: 65,
      thickness: 1.6,
      solderMaskColor: '#1e3a8a', // Deep Royal Blue
      copperLayerCount: 2,
      gridSpacing: 2.54,
      shape: 'rectangle',
    },
    metadata: {
      difficulty: 'Trung bình',
      category: 'IC Định thời & Dao động',
      slug: 'den-nhay-dieu-chinh-toc-do',
      version: '1.0.0',
      isTemplate: true,
      learningObjectives: [
        'Phân tích chu kỳ dao động nạp/xả tụ điện C qua biến trở và điện trở',
        'Khảo sát xung vuông đầu ra chân OUT của IC định thời NE555',
        'Thao tác Resize Board để tối ưu bố cục mạch theo tiêu chuẩn công nghiệp',
      ],
      requiredComponents: [
        'dc-source',
        'ne555',
        'resistor',
        'potentiometer',
        'capacitor',
        'led',
        'switch',
        'connector',
      ],
      simulationSupport: true,
    },
    components: [
      {
        instanceId: 'src-pwr',
        definitionId: 'dc-source',
        name: 'Nguồn 5V',
        position: { x: -34, y: 0, z: -14 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 5.0 },
      },
      {
        instanceId: 'sw-power',
        definitionId: 'switch',
        name: 'Khóa Nguồn',
        position: { x: -34, y: 0, z: 14 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { type: 'slide' },
      },
      {
        instanceId: 'ic-timer',
        definitionId: 'ne555',
        name: 'IC NE555',
        position: { x: -6, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { mode: 'astable' },
      },
      {
        instanceId: 'pot-speed',
        definitionId: 'potentiometer',
        name: 'POT Chỉnh Tốc Độ',
        position: { x: -6, y: 0, z: -18 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { maxResistance: 100000 },
      },
      {
        instanceId: 'cap-timing',
        definitionId: 'capacitor',
        name: 'Tụ 100µF',
        position: { x: -6, y: 0, z: 18 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { capacitance: 100 },
      },
      {
        instanceId: 'res-pullup',
        definitionId: 'resistor',
        name: 'R1 1kΩ',
        position: { x: 14, y: 0, z: -18 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { resistance: 1000 },
      },
      {
        instanceId: 'res-limit',
        definitionId: 'resistor',
        name: 'R2 330Ω',
        position: { x: 14, y: 0, z: 6 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { resistance: 330 },
      },
      {
        instanceId: 'led-blink',
        definitionId: 'led',
        name: 'LED Xanh Dương',
        position: { x: 32, y: 0, z: 6 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { color: 'blue' },
      },
      {
        instanceId: 'term-out',
        definitionId: 'connector',
        name: 'Terminal Ra',
        position: { x: 32, y: 0, z: -16 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: {},
      },
    ],
    connections: [
      {
        id: 'c1-pwr-sw',
        fromComponentId: 'src-pwr',
        fromPinId: 'vcc',
        toComponentId: 'sw-power',
        toPinId: 'pin1',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c2-sw-ic-vcc',
        fromComponentId: 'sw-power',
        fromPinId: 'pin2',
        toComponentId: 'ic-timer',
        toPinId: 'vcc',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c3-sw-res-pull',
        fromComponentId: 'sw-power',
        fromPinId: 'pin2',
        toComponentId: 'res-pullup',
        toPinId: 'pin1',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c4-res-pot',
        fromComponentId: 'res-pullup',
        fromPinId: 'pin2',
        toComponentId: 'pot-speed',
        toPinId: 'pin1',
        wireColor: '#f59e0b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c5-pot-trig',
        fromComponentId: 'pot-speed',
        fromPinId: 'wiper',
        toComponentId: 'ic-timer',
        toPinId: 'trig',
        wireColor: '#f59e0b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c6-trig-cap',
        fromComponentId: 'ic-timer',
        toComponentId: 'cap-timing',
        fromPinId: 'trig',
        toPinId: 'pin_pos',
        wireColor: '#eab308',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c7-cap-gnd',
        fromComponentId: 'cap-timing',
        fromPinId: 'pin_neg',
        toComponentId: 'src-pwr',
        toPinId: 'gnd',
        wireColor: '#1e293b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c8-ic-gnd',
        fromComponentId: 'ic-timer',
        fromPinId: 'gnd',
        toComponentId: 'src-pwr',
        toPinId: 'gnd',
        wireColor: '#1e293b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c9-ic-out-res',
        fromComponentId: 'ic-timer',
        fromPinId: 'out',
        toComponentId: 'res-limit',
        toPinId: 'pin1',
        wireColor: '#06b6d4',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c10-res-led',
        fromComponentId: 'res-limit',
        fromPinId: 'pin2',
        toComponentId: 'led-blink',
        toPinId: 'anode',
        wireColor: '#38bdf8',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c11-led-gnd',
        fromComponentId: 'led-blink',
        fromPinId: 'cathode',
        toComponentId: 'src-pwr',
        toPinId: 'gnd',
        wireColor: '#1e293b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c12-term-vcc',
        fromComponentId: 'term-out',
        fromPinId: 'pin1',
        toComponentId: 'sw-power',
        toPinId: 'pin2',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c13-term-gnd',
        fromComponentId: 'term-out',
        fromPinId: 'pin2',
        toComponentId: 'src-pwr',
        toPinId: 'gnd',
        wireColor: '#1e293b',
        wireStyle: 'orthogonal',
      },
    ],
    wireRoutes: [],
    createdAt: '2026-09-14T00:00:00.000Z',
    updatedAt: '2026-09-14T00:00:00.000Z',
  },

  // --- PROJECT 3 (KHÓ - SHOWCASE): HỆ THỐNG CỬA THÔNG MINH UNO R3 ---
  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'sample-smart-door-uno',
    name: 'Hệ thống cửa thông minh UNO R3',
    description: 'Showcase tổng hợp: Cảm biến siêu âm HC-SR04 phát hiện người, Arduino UNO R3 điều khiển Servo mở cửa, đèn RGB báo trạng thái và Còi Buzzer âm báo trên bo mạch vát góc kỹ thuật Board Cut Tool.',
    revision: 1,
    units: 'mm',
    board: {
      width: 160,
      depth: 110,
      thickness: 1.6,
      solderMaskColor: '#0f172a', // Obsidian Tech Black
      copperLayerCount: 2,
      gridSpacing: 2.54,
      shape: 'polygon',
      // Showcase of Board Cut Tool: Corner chamfer cut
      outline: [
        { x: -80, z: -55 },
        { x: 45, z: -55 },
        { x: 80, z: -20 },
        { x: 80, z: 55 },
        { x: -80, z: 55 },
      ],
      cutHistory: [
        {
          path: [
            { x: 45, z: -55 },
            { x: 80, z: -20 },
          ],
          timestamp: '2026-09-14T00:00:00.000Z',
        },
      ],
    },
    metadata: {
      difficulty: 'Khó',
      category: 'Vi điều khiển & Tự động hóa IoT',
      slug: 'he-thong-cua-thong-minh-uno-r3',
      version: '1.0.0',
      isTemplate: true,
      learningObjectives: [
        'Giao tiếp cảm biến siêu âm phát sóng Trig và bắt phản xạ Echo',
        'Tạo tín hiệu điều chế độ rộng xung (PWM) góc quay Servo cơ khí',
        'Điều khiển LED đa màu RGB hiển thị trạng thái An toàn / Báo động',
        'Phát âm thanh tần số cảnh báo bằng Còi chíp Buzzer 5V',
        'Ứng dụng Board Cut Tool tạo bo mạch vát góc công nghiệp theo hộp chứa',
      ],
      requiredComponents: [
        'arduino-uno',
        'ultrasonic-sensor',
        'servo-motor',
        'rgb-led',
        'buzzer',
        'resistor',
        'pushbutton',
        'dc-source',
        'connector',
      ],
      simulationSupport: true,
    },
    components: [
      {
        instanceId: 'uno-main',
        definitionId: 'arduino-uno',
        name: 'Arduino UNO R3',
        position: { x: -24, y: 0, z: 8 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { codeProgram: 'button_read' },
      },
      {
        instanceId: 'sonar-eye',
        definitionId: 'ultrasonic-sensor',
        name: 'Siêu âm HC-SR04',
        position: { x: -44, y: 0, z: -35 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { distanceCm: 25 },
      },
      {
        instanceId: 'servo-door',
        definitionId: 'servo-motor',
        name: 'Servo Cửa SG90',
        position: { x: 48, y: 0, z: -5 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { targetAngle: 90 },
      },
      {
        instanceId: 'rgb-lamp',
        definitionId: 'rgb-led',
        name: 'RGB Báo Trạng Thái',
        position: { x: 48, y: 0, z: 30 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { colorState: 'green' },
      },
      {
        instanceId: 'buzzer-alarm',
        definitionId: 'buzzer',
        name: 'Còi Báo Động',
        position: { x: 12, y: 0, z: -35 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: {},
      },
      {
        instanceId: 'btn-manual',
        definitionId: 'pushbutton',
        name: 'Nút Mở Thủ Công',
        position: { x: 48, y: 0, z: -35 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: {},
      },
      {
        instanceId: 'r-rgb-g',
        definitionId: 'resistor',
        name: 'R1 220Ω (Green)',
        position: { x: 25, y: 0, z: 28 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { resistance: 220 },
      },
      {
        instanceId: 'r-rgb-r',
        definitionId: 'resistor',
        name: 'R2 220Ω (Red)',
        position: { x: 25, y: 0, z: 36 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { resistance: 220 },
      },
      {
        instanceId: 'pwr-dc',
        definitionId: 'dc-source',
        name: 'Nguồn Adapter 5V',
        position: { x: -66, y: 0, z: 28 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 5.0 },
      },
      {
        instanceId: 'term-ext',
        definitionId: 'connector',
        name: 'Cọc Nối Nguồn Ngoài',
        position: { x: -66, y: 0, z: -10 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: {},
      },
    ],
    connections: [
      {
        id: 'c1-pwr-uno',
        fromComponentId: 'pwr-dc',
        fromPinId: 'vcc',
        toComponentId: 'uno-main',
        toPinId: 'pin_5v',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c2-pwr-gnd',
        fromComponentId: 'pwr-dc',
        fromPinId: 'gnd',
        toComponentId: 'uno-main',
        toPinId: 'pin_gnd',
        wireColor: '#0f172a',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c3-uno-sonar-vcc',
        fromComponentId: 'uno-main',
        fromPinId: 'pin_5v',
        toComponentId: 'sonar-eye',
        toPinId: 'vcc',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c4-uno-sonar-gnd',
        fromComponentId: 'uno-main',
        fromPinId: 'pin_gnd',
        toComponentId: 'sonar-eye',
        toPinId: 'gnd',
        wireColor: '#0f172a',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c5-sonar-trig',
        fromComponentId: 'sonar-eye',
        fromPinId: 'trig',
        toComponentId: 'uno-main',
        toPinId: 'pin_d12',
        wireColor: '#f59e0b',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c6-sonar-echo',
        fromComponentId: 'sonar-eye',
        fromPinId: 'echo',
        toComponentId: 'uno-main',
        toPinId: 'pin_d13',
        wireColor: '#10b981',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c7-uno-servo-vcc',
        fromComponentId: 'uno-main',
        fromPinId: 'pin_5v',
        toComponentId: 'servo-door',
        toPinId: 'vcc',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c8-uno-servo-gnd',
        fromComponentId: 'uno-main',
        fromPinId: 'pin_gnd',
        toComponentId: 'servo-door',
        toPinId: 'gnd',
        wireColor: '#0f172a',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c9-uno-servo-sig',
        fromComponentId: 'uno-main',
        fromPinId: 'pin_d12',
        toComponentId: 'servo-door',
        toPinId: 'signal',
        wireColor: '#f97316',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c10-uno-buzz-vcc',
        fromComponentId: 'uno-main',
        fromPinId: 'pin_d13',
        toComponentId: 'buzzer-alarm',
        toPinId: 'pin_pos',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c11-uno-buzz-gnd',
        fromComponentId: 'uno-main',
        fromPinId: 'pin_gnd',
        toComponentId: 'buzzer-alarm',
        toPinId: 'pin_neg',
        wireColor: '#0f172a',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c12-uno-rgb-g',
        fromComponentId: 'uno-main',
        fromPinId: 'pin_d13',
        toComponentId: 'r-rgb-g',
        toPinId: 'pin1',
        wireColor: '#22c55e',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c13-res-rgb-green',
        fromComponentId: 'r-rgb-g',
        fromPinId: 'pin2',
        toComponentId: 'rgb-lamp',
        toPinId: 'green',
        wireColor: '#22c55e',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c14-rgb-cathode-gnd',
        fromComponentId: 'rgb-lamp',
        fromPinId: 'cathode',
        toComponentId: 'uno-main',
        toPinId: 'pin_gnd',
        wireColor: '#0f172a',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c15-btn-uno',
        fromComponentId: 'btn-manual',
        fromPinId: 'pin1',
        toComponentId: 'uno-main',
        toPinId: 'pin_d12',
        wireColor: '#38bdf8',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c16-btn-gnd',
        fromComponentId: 'btn-manual',
        fromPinId: 'pin2',
        toComponentId: 'uno-main',
        toPinId: 'pin_gnd',
        wireColor: '#0f172a',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c17-term-pwr',
        fromComponentId: 'term-ext',
        fromPinId: 'pin1',
        toComponentId: 'pwr-dc',
        toPinId: 'vcc',
        wireColor: '#ef4444',
        wireStyle: 'orthogonal',
      },
      {
        id: 'c18-term-gnd',
        fromComponentId: 'term-ext',
        fromPinId: 'pin2',
        toComponentId: 'pwr-dc',
        toPinId: 'gnd',
        wireColor: '#0f172a',
        wireStyle: 'orthogonal',
      },
    ],
    wireRoutes: [],
    createdAt: '2026-09-14T00:00:00.000Z',
    updatedAt: '2026-09-14T00:00:00.000Z',
  },

  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'demo-led-single',
    name: 'Mạch LED phát quang cơ bản',
    description: 'Mạch thực hành kinh điển với nguồn pin 5V DC, điện trở 220Ω và đèn LED đỏ.',
    revision: 1,
    units: 'mm',
    board: {
      width: 140,
      depth: 90,
      thickness: 1.6,
      solderMaskColor: '#104936',
      copperLayerCount: 2,
      gridSpacing: 2.54,
    },
    components: [
      {
        instanceId: 'src-1',
        definitionId: 'dc-source',
        name: 'Nguồn 5V',
        position: { x: -40, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 5.0 },
      },
      {
        instanceId: 'r-1',
        definitionId: 'resistor',
        name: 'R1 (220Ω)',
        position: { x: 0, y: 0, z: -15 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { resistance: 220 },
      },
      {
        instanceId: 'led-1',
        definitionId: 'led',
        name: 'LED Đỏ',
        position: { x: 40, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { color: 'red' },
      },
    ],
    connections: [
      {
        id: 'conn-1',
        fromComponentId: 'src-1',
        fromPinId: 'vcc',
        toComponentId: 'r-1',
        toPinId: 'pin1',
        wireColor: '#ef4444',
      },
      {
        id: 'conn-2',
        fromComponentId: 'r-1',
        fromPinId: 'pin2',
        toComponentId: 'led-1',
        toPinId: 'anode',
        wireColor: '#f59e0b',
      },
      {
        id: 'conn-3',
        fromComponentId: 'led-1',
        fromPinId: 'cathode',
        toComponentId: 'src-1',
        toPinId: 'gnd',
        wireColor: '#1e293b',
      },
    ],
    wireRoutes: [],
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'demo-switch-led',
    name: 'Mạch công tắc điều khiển đèn',
    description: 'Hệ thống đóng ngắt mạch dùng công tắc gạt slide switch nối tiếp với LED xanh.',
    revision: 1,
    units: 'mm',
    board: {
      width: 150,
      depth: 100,
      thickness: 1.6,
      solderMaskColor: '#0e3952',
      copperLayerCount: 2,
      gridSpacing: 2.54,
    },
    components: [
      {
        instanceId: 'pwr-main',
        definitionId: 'dc-source',
        name: 'Pin 5V',
        position: { x: -50, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 5.0 },
      },
      {
        instanceId: 'sw-toggle',
        definitionId: 'switch',
        name: 'SW1',
        position: { x: -20, y: 0, z: -20 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { type: 'slide' },
        state: { open: false },
      },
      {
        instanceId: 'res-limit',
        definitionId: 'resistor',
        name: 'R1 (330Ω)',
        position: { x: 15, y: 0, z: -20 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { resistance: 330 },
      },
      {
        instanceId: 'led-green',
        definitionId: 'led',
        name: 'LED Xanh',
        position: { x: 50, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { color: 'green' },
      },
    ],
    connections: [
      {
        id: 'c-vcc',
        fromComponentId: 'pwr-main',
        fromPinId: 'vcc',
        toComponentId: 'sw-toggle',
        toPinId: 'pin1',
        wireColor: '#ef4444',
      },
      {
        id: 'c-sw-res',
        fromComponentId: 'sw-toggle',
        fromPinId: 'pin2',
        toComponentId: 'res-limit',
        toPinId: 'pin1',
        wireColor: '#f59e0b',
      },
      {
        id: 'c-res-led',
        fromComponentId: 'res-limit',
        fromPinId: 'pin2',
        toComponentId: 'led-green',
        toPinId: 'anode',
        wireColor: '#10b981',
      },
      {
        id: 'c-gnd',
        fromComponentId: 'led-green',
        fromPinId: 'cathode',
        toComponentId: 'pwr-main',
        toPinId: 'gnd',
        wireColor: '#0f172a',
      },
    ],
    wireRoutes: [],
    createdAt: '2026-09-02T12:30:00.000Z',
    updatedAt: '2026-09-02T12:30:00.000Z',
  },
  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'demo-potentiometer-control',
    name: 'Mạch chiết áp chỉnh độ sáng Potentiometer',
    description: 'Thí nghiệm phân chia điện áp và chỉnh dòng qua con chạy biến trở xoay.',
    revision: 1,
    units: 'mm',
    board: {
      width: 140,
      depth: 95,
      thickness: 1.6,
      solderMaskColor: '#1a3328',
      copperLayerCount: 2,
      gridSpacing: 2.54,
    },
    components: [
      {
        instanceId: 'pwr-pot',
        definitionId: 'dc-source',
        name: 'Nguồn 5V',
        position: { x: -45, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 5.0 },
      },
      {
        instanceId: 'pot-1',
        definitionId: 'potentiometer',
        name: 'POT 10k',
        position: { x: 0, y: 0, z: -15 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { maxResistance: 10000 },
      },
      {
        instanceId: 'led-yellow',
        definitionId: 'led',
        name: 'LED Vàng',
        position: { x: 45, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { color: 'yellow' },
      },
    ],
    connections: [
      {
        id: 'cp-1',
        fromComponentId: 'pwr-pot',
        fromPinId: 'vcc',
        toComponentId: 'pot-1',
        toPinId: 'pin1',
        wireColor: '#ef4444',
      },
      {
        id: 'cp-2',
        fromComponentId: 'pot-1',
        fromPinId: 'wiper',
        toComponentId: 'led-yellow',
        toPinId: 'anode',
        wireColor: '#eab308',
      },
      {
        id: 'cp-3',
        fromComponentId: 'led-yellow',
        fromPinId: 'cathode',
        toComponentId: 'pwr-pot',
        toPinId: 'gnd',
        wireColor: '#1e293b',
      },
    ],
    wireRoutes: [],
    createdAt: '2026-09-03T15:00:00.000Z',
    updatedAt: '2026-09-03T15:00:00.000Z',
  },
  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'demo-buzzer-alarm',
    name: 'Mạch còi báo động khẩn cấp Buzzer',
    description: 'Hệ thống âm thanh cảnh báo 85dB kết hợp nút bấm tác động nhanh và đèn LED báo hiệu.',
    revision: 1,
    units: 'mm',
    board: {
      width: 140,
      depth: 90,
      thickness: 1.6,
      solderMaskColor: '#450a0a',
      copperLayerCount: 2,
      gridSpacing: 2.54,
    },
    components: [
      {
        instanceId: 'pwr-bz',
        definitionId: 'dc-source',
        name: 'Nguồn 5V',
        position: { x: -45, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 5.0 },
      },
      {
        instanceId: 'btn-bz',
        definitionId: 'pushbutton',
        name: 'Nút nhấn Báo động',
        position: { x: -10, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { pressed: true },
      },
      {
        instanceId: 'buz-1',
        definitionId: 'buzzer',
        name: 'Còi Buzzer 5V',
        position: { x: 30, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: {},
      },
    ],
    connections: [
      { id: 'cbz-1', fromComponentId: 'pwr-bz', fromPinId: 'vcc', toComponentId: 'btn-bz', toPinId: 'pin1', wireColor: '#ef4444' },
      { id: 'cbz-2', fromComponentId: 'btn-bz', fromPinId: 'pin2', toComponentId: 'buz-1', toPinId: 'pin_pos', wireColor: '#f59e0b' },
      { id: 'cbz-3', fromComponentId: 'buz-1', fromPinId: 'pin_neg', toComponentId: 'pwr-bz', toPinId: 'gnd', wireColor: '#1e293b' },
    ],
    wireRoutes: [],
    createdAt: '2026-09-05T10:00:00.000Z',
    updatedAt: '2026-09-05T10:00:00.000Z',
  },
  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'demo-ldr-nightlight',
    name: 'Mạch đèn tự động cảm biến quang LDR',
    description: 'Cầu phân áp quang trở LDR phát hiện ánh sáng yếu và tự động thắp sáng đèn LED trắng.',
    revision: 1,
    units: 'mm',
    board: {
      width: 150,
      depth: 100,
      thickness: 1.6,
      solderMaskColor: '#1e1b4b',
      copperLayerCount: 2,
      gridSpacing: 2.54,
    },
    components: [
      {
        instanceId: 'pwr-ldr',
        definitionId: 'dc-source',
        name: 'Nguồn 5V',
        position: { x: -50, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 5.0 },
      },
      {
        instanceId: 'ldr-sens',
        definitionId: 'ldr',
        name: 'Quang trở LDR',
        position: { x: -15, y: 0, z: -15 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { lux: 80 },
      },
      {
        instanceId: 'res-pull',
        definitionId: 'resistor',
        name: 'R1 10kΩ',
        position: { x: 15, y: 0, z: -15 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { resistance: 10000 },
      },
      {
        instanceId: 'led-light',
        definitionId: 'led',
        name: 'LED Trắng',
        position: { x: 45, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { color: 'white' },
      },
    ],
    connections: [
      { id: 'cldr-1', fromComponentId: 'pwr-ldr', fromPinId: 'vcc', toComponentId: 'ldr-sens', toPinId: 'pin1', wireColor: '#ef4444' },
      { id: 'cldr-2', fromComponentId: 'ldr-sens', fromPinId: 'pin2', toComponentId: 'res-pull', toPinId: 'pin1', wireColor: '#f59e0b' },
      { id: 'cldr-3', fromComponentId: 'res-pull', fromPinId: 'pin2', toComponentId: 'led-light', toPinId: 'anode', wireColor: '#10b981' },
      { id: 'cldr-4', fromComponentId: 'led-light', fromPinId: 'cathode', toComponentId: 'pwr-ldr', toPinId: 'gnd', wireColor: '#1e293b' },
    ],
    wireRoutes: [],
    createdAt: '2026-09-06T12:00:00.000Z',
    updatedAt: '2026-09-06T12:00:00.000Z',
  },
  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'demo-ne555-blinker',
    name: 'Mạch dao động đa hài tạo xung IC 555',
    description: 'IC định thời NE555 kinh điển kết hợp tụ hóa 100µF tạo xung vuông nháy LED nhịp nhàng.',
    revision: 1,
    units: 'mm',
    board: {
      width: 160,
      depth: 110,
      thickness: 1.6,
      solderMaskColor: '#14532d',
      copperLayerCount: 2,
      gridSpacing: 2.54,
    },
    components: [
      {
        instanceId: 'pwr-555',
        definitionId: 'dc-source',
        name: 'Nguồn 9V',
        position: { x: -60, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 9.0 },
      },
      {
        instanceId: 'ic-555',
        definitionId: 'ne555',
        name: 'NE555 Timer',
        position: { x: -10, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: {},
      },
      {
        instanceId: 'cap-555',
        definitionId: 'capacitor',
        name: 'Tụ 100µF',
        position: { x: -10, y: 0, z: -25 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { capacitance: 0.0001 },
      },
      {
        instanceId: 'r-555',
        definitionId: 'resistor',
        name: 'R1 10kΩ',
        position: { x: 20, y: 0, z: -15 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { resistance: 10000 },
      },
      {
        instanceId: 'led-555',
        definitionId: 'led',
        name: 'LED Xung Ra',
        position: { x: 50, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { color: 'green' },
      },
    ],
    connections: [
      { id: 'c555-1', fromComponentId: 'pwr-555', fromPinId: 'vcc', toComponentId: 'ic-555', toPinId: 'vcc', wireColor: '#ef4444' },
      { id: 'c555-2', fromComponentId: 'ic-555', fromPinId: 'gnd', toComponentId: 'pwr-555', toPinId: 'gnd', wireColor: '#1e293b' },
      { id: 'c555-3', fromComponentId: 'ic-555', fromPinId: 'out', toComponentId: 'r-555', toPinId: 'pin1', wireColor: '#f59e0b' },
      { id: 'c555-4', fromComponentId: 'r-555', fromPinId: 'pin2', toComponentId: 'led-555', toPinId: 'anode', wireColor: '#10b981' },
      { id: 'c555-5', fromComponentId: 'led-555', fromPinId: 'cathode', toComponentId: 'pwr-555', toPinId: 'gnd', wireColor: '#1e293b' },
    ],
    wireRoutes: [],
    createdAt: '2026-09-08T14:00:00.000Z',
    updatedAt: '2026-09-08T14:00:00.000Z',
  },
  {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    projectId: 'demo-relay-controller',
    name: 'Mạch điều khiển Rơ-le cách ly tải nặng',
    description: 'Điều khiển đóng cắt thiết bị bằng Rơ-le Songle 5V có diode 1N4007 dập xung tự cảm Flyback.',
    revision: 1,
    units: 'mm',
    board: {
      width: 150,
      depth: 100,
      thickness: 1.6,
      solderMaskColor: '#0c4a6e',
      copperLayerCount: 2,
      gridSpacing: 2.54,
    },
    components: [
      {
        instanceId: 'pwr-rel',
        definitionId: 'dc-source',
        name: 'Nguồn 5V',
        position: { x: -55, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { voltage: 5.0 },
      },
      {
        instanceId: 'sw-rel',
        definitionId: 'switch',
        name: 'Công tắc Kích',
        position: { x: -25, y: 0, z: -15 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { type: 'slide' },
        state: { open: false },
      },
      {
        instanceId: 'relay-main',
        definitionId: 'relay',
        name: 'Rơ-le Songle 5V',
        position: { x: 10, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: {},
      },
      {
        instanceId: 'led-load',
        definitionId: 'led',
        name: 'Đèn Tải',
        position: { x: 50, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        parameters: { color: 'blue' },
      },
    ],
    connections: [
      { id: 'crel-1', fromComponentId: 'pwr-rel', fromPinId: 'vcc', toComponentId: 'sw-rel', toPinId: 'pin1', wireColor: '#ef4444' },
      { id: 'crel-2', fromComponentId: 'sw-rel', fromPinId: 'pin2', toComponentId: 'relay-main', toPinId: 'coil_pos', wireColor: '#f59e0b' },
      { id: 'crel-3', fromComponentId: 'relay-main', fromPinId: 'coil_neg', toComponentId: 'pwr-rel', toPinId: 'gnd', wireColor: '#1e293b' },
    ],
    wireRoutes: [],
    createdAt: '2026-09-09T08:00:00.000Z',
    updatedAt: '2026-09-09T08:00:00.000Z',
  },
];
