import { Course } from './types';
import { createDefaultProjectDocument } from '../project/document';
import { ProjectDocument } from '../project/types';

export const COURSES: Course[] = [
  {
    id: 'course-uno-r3-basic',
    title: 'Khóa học UNO R3 - Mạch điện tử cơ bản',
    slug: 'uno-r3-mach-dien-tu-co-ban',
    tagline: 'Lộ trình 8 chương bài bản từ thắp sáng LED, nút bấm, cảm biến quang, âm thanh đến IC NE555 và vi điều khiển.',
    description:
      'Khóa học thực hành cốt lõi dành cho sinh viên, kỹ sư và người yêu thích điện tử. Đi từ nguyên lý mạch phân cực cơ bản đến thiết kế các hệ thống cảm biến thông minh, điều khiển tải cách ly an toàn và tạo nhịp dao động xung trên nền tảng 3D tương tác.',
    author: {
      id: 'author-huynh-phong',
      name: 'Huỳnh Phong',
      role: 'Kỹ sư Vi mạch & Giảng viên STEM',
      bio: 'Chuyên gia Thiết kế Vi mạch và Giảng viên Hệ thống Nhúng & Mạch 3D',
    },
    instructor: {
      name: 'Huỳnh Phong',
      role: 'Kỹ sư Vi mạch & Giảng viên STEM',
    },
    price: 799000,
    originalPrice: 1200000,
    isFree: false,
    currency: 'VND',
    level: 'Cơ bản',
    category: 'stem',
    duration: '8.0 giờ',
    lessonCount: 8,
    rating: 5.0,
    reviewsCount: 2840,
    studentsCount: 6120,
    thumbnailGradient: 'from-cyan-600 via-blue-600 to-indigo-700',
    badge: 'Khóa học Đề xuất',
    highlights: [
      'Chương 1: Thắp sáng LED đỏ an toàn với điện trở hạn dòng 220Ω',
      'Chương 2: Mạch đóng ngắt điều khiển qua công tắc cơ khí',
      'Chương 3: Cầu phân áp biến thiên với Biến trở 10kΩ',
      'Chương 4: Cảm biến quang trở LDR tự động bật đèn khi trời tối',
      'Chương 5: Còi báo động Buzzer 5V & Mạch phát tín hiệu khẩn cấp',
      'Chương 6: Giám sát môi trường với cảm biến nhiệt độ LM35 (10mV/°C)',
      'Chương 7: Rơ-le điều khiển cách ly tải công suất cao an toàn',
      'Chương 8: Tạo nhịp dao động đa hài với IC định thời NE555',
    ],
    syllabus: [
      {
        id: 'syl-uno-1',
        title: 'Chương 1: Thắp sáng đèn LED đỏ đầu tiên với Điện trở hạn dòng',
        duration: '35 phút',
        isPracticalLab: true,
        labGoal: 'Đặt Nguồn 5V, Điện trở 220Ω và LED đỏ lên bo mạch, nối dây khép kín và bật mô phỏng.',
        labLessonId: 'lesson-1-basic-led',
      },
      {
        id: 'syl-uno-2',
        title: 'Chương 2: Điều khiển bật/tắt bằng Công tắc SPST',
        duration: '40 phút',
        isPracticalLab: true,
        labGoal: 'Thêm công tắc gạt SPST vào chuỗi dẫn nguồn để đóng ngắt bóng LED.',
        labLessonId: 'lesson-2-switch-control',
      },
      {
        id: 'syl-uno-3',
        title: 'Chương 3: Điều chỉnh độ sáng mượt mà với Biến trở (Potentiometer)',
        duration: '45 phút',
        isPracticalLab: true,
        labGoal: 'Nối cầu phân áp biến trở 10kΩ để chia điện áp cấp cho LED.',
        labLessonId: 'lesson-3-pot-control',
      },
      {
        id: 'syl-uno-4',
        title: 'Chương 4: Cảm biến quang trở LDR - Đèn thông minh tự động trời tối',
        duration: '50 phút',
        isPracticalLab: true,
        labGoal: 'Ghép LDR với điện trở kéo để kích hoạt đèn LED khi ánh sáng yếu.',
        labLessonId: 'lesson-4-ldr-dark-sensor',
      },
      {
        id: 'syl-uno-5',
        title: 'Chương 5: Còi báo động Buzzer & Mạch cảnh báo âm thanh 85dB',
        duration: '45 phút',
        isPracticalLab: true,
        labGoal: 'Kết nối còi chíp Buzzer 5V và nút nhấn khẩn cấp để phát âm thanh.',
        labLessonId: 'lesson-5-buzzer-alarm',
      },
      {
        id: 'syl-uno-6',
        title: 'Chương 6: Cảm biến nhiệt độ LM35 & Giám sát nhiệt độ môi trường',
        duration: '55 phút',
        isPracticalLab: true,
        labGoal: 'Cấp nguồn cho cảm biến LM35 và đo điện áp xuất ra 10mV/°C.',
        labLessonId: 'lesson-6-temp-lm35',
      },
      {
        id: 'syl-uno-7',
        title: 'Chương 7: Rơ-le (Relay) đóng cắt thiết bị công suất cao cách ly',
        duration: '60 phút',
        isPracticalLab: true,
        labGoal: 'Dùng tín hiệu điều khiển kích cuộn hút rơ-le để đóng ngắt tiếp điểm NO an toàn.',
        labLessonId: 'lesson-7-relay-isolation',
      },
      {
        id: 'syl-uno-8',
        title: 'Chương 8: IC định thời NE555 & Mạch dao động đa hài tạo xung nhịp',
        duration: '75 phút',
        isPracticalLab: true,
        labGoal: 'Mắc IC NE555 cùng tụ điện 100µF và điện trở để tạo xung vuông tự động chớp LED.',
        labLessonId: 'lesson-8-ne555-oscillator',
      },
    ],
    createLabProject: (labId) => {
      const doc = createDefaultProjectDocument('Thực hành: UNO R3 - Mạch điện tử cơ bản');
      doc.components = [
        {
          instanceId: 'pwr-1',
          definitionId: 'dc-source',
          name: 'Nguồn 5V',
          position: { x: -45, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { voltage: 5.0 },
        },
        {
          instanceId: 'res-1',
          definitionId: 'resistor',
          name: 'R1 (220Ω)',
          position: { x: -5, y: 0, z: -15 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { resistance: 220 },
        },
        {
          instanceId: 'led-1',
          definitionId: 'led',
          name: 'LED Đỏ',
          position: { x: 35, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { color: 'red' },
        },
      ];
      return doc;
    },
  },
  {
    id: 'course-intro-stem-3d',
    title: 'Nhập Môn Mạch Điện Tử & Mô Phỏng Thực Tế 3D',
    slug: 'nhap-mon-mach-dien-tu-3d',
    tagline: 'Làm quen trực quan với nguồn DC, điện trở, LED và luật Ohm trên không gian 3D tương tác.',
    description:
      'Khóa học nền tảng dành cho người mới bắt đầu hoặc học sinh, sinh viên ngành kỹ thuật. Tiếp cận các khái niệm điện áp, dòng điện, công suất thông qua thực hành lắp ráp linh kiện 3D trực quan, chống cháy nổ và quan sát dòng chảy điện áp thực tế.',
    author: {
      id: 'author-nguyen-thanh-luan',
      name: 'KS. Nguyễn Thành Luân',
      role: 'Kỹ sư Phần cứng & Giảng viên STEM Robotics',
    },
    instructor: {
      name: 'KS. Nguyễn Thành Luân',
      role: 'Kỹ sư Phần cứng & Giảng viên STEM Robotics',
    },
    price: 0,
    currency: 'VND',
    isFree: true,
    level: 'Cơ bản',
    category: 'stem',
    duration: '3.5 giờ',
    lessonCount: 4,
    rating: 4.9,
    reviewsCount: 1420,
    studentsCount: 3850,
    thumbnailGradient: 'from-cyan-600 via-teal-600 to-emerald-700',
    badge: 'Miễn phí 100%',
    highlights: [
      'Hiểu rõ bản chất điện áp (V), dòng điện (I) và điện trở (R)',
      'Nắm vững cách tính điện trở hạn dòng bảo vệ linh kiện LED',
      'Thực hành nối dây mạch kín trực tiếp trên không gian 3D',
      'Mô phỏng tức thì phát hiện lỗi nối tắt (Short circuit)',
    ],
    syllabus: [
      {
        id: 'syl-1-1',
        title: 'Bài 1: Khái niệm Nguồn DC, Cực tính VCC & GND',
        duration: '20 phút',
        isPracticalLab: false,
      },
      {
        id: 'syl-1-2',
        title: 'Bài 2: Thực hành 3D - Thắp sáng đèn LED đỏ đầu tiên',
        duration: '35 phút',
        isPracticalLab: true,
        labGoal: 'Đặt Nguồn 5V, Điện trở 220Ω và LED đỏ lên bo mạch, nối dây khép kín và bật mô phỏng.',
        labLessonId: 'lesson-1-basic-led',
      },
      {
        id: 'syl-1-3',
        title: 'Bài 3: Định luật Ohm & Phép tính sụt áp trên tải',
        duration: '25 phút',
        isPracticalLab: false,
      },
      {
        id: 'syl-1-4',
        title: 'Bài 4: Thực hành 3D - Điều khiển đèn với Công tắc cơ học',
        duration: '40 phút',
        isPracticalLab: true,
        labGoal: 'Thêm công tắc gạt SPST vào chuỗi dẫn nguồn để bật/tắt bóng LED.',
        labLessonId: 'lesson-2-switch-led',
      },
    ],
    createLabProject: (labId) => {
      const doc = createDefaultProjectDocument('Thực hành: Khóa học Nhập môn 3D');
      doc.components = [
        {
          instanceId: 'pwr-1',
          definitionId: 'dc-source',
          name: 'Nguồn 5V',
          position: { x: -45, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { voltage: 5.0 },
        },
        {
          instanceId: 'res-1',
          definitionId: 'resistor',
          name: 'R1 (220Ω)',
          position: { x: -5, y: 0, z: -15 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { resistance: 220 },
        },
        {
          instanceId: 'led-1',
          definitionId: 'led',
          name: 'LED Đỏ',
          position: { x: 35, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { color: 'red' },
        },
      ];
      return doc;
    },
  },
  {
    id: 'course-switch-relays',
    title: 'Mạch Đóng Cắt Tự Động: Công Tắc, Relay & Bảo Vệ Mạch',
    slug: 'mach-dong-cat-cong-tac-relay',
    tagline: 'Làm chủ các mạch điều khiển cách ly, rơle đóng cắt công suất và chuyển mạch đa kênh.',
    description:
      'Tìm hiểu các phương pháp đóng cắt mạch điện an toàn. Phân biệt công tắc cơ khí đơn cực, công tắc hai chiều cầu thang, và relay điện từ đóng ngắt dòng lớn được cách ly quang và diode dập xung ngược.',
    author: {
      id: 'author-tran-hoang-nam',
      name: 'ThS. Trần Hoàng Nam',
      role: 'Chuyên gia Tự động hóa & Kỹ thuật điện tử',
    },
    instructor: {
      name: 'ThS. Trần Hoàng Nam',
      role: 'Chuyên gia Tự động hóa & Kỹ thuật điện tử',
    },
    price: 0,
    currency: 'VND',
    isFree: true,
    level: 'Cơ bản',
    category: 'analog',
    duration: '4.0 giờ',
    lessonCount: 5,
    rating: 4.85,
    reviewsCount: 890,
    studentsCount: 2200,
    thumbnailGradient: 'from-amber-600 via-orange-600 to-rose-700',
    badge: 'Miễn phí 100%',
    highlights: [
      'Nguyên lý tiếp điểm NO (Normally Open) và NC (Normally Closed)',
      'Thiết kế mạch đèn cầu thang 2 công tắc gạt đảo chiều',
      'Ứng dụng Relay đóng cắt tải công suất cao cách ly an toàn',
      'Diode Flyback chống xung điện áp cảm ứng cuộn hút',
    ],
    syllabus: [
      {
        id: 'syl-2-1',
        title: 'Bài 1: Tổng quan cơ cấu tiếp điểm cơ khí và hồ quang',
        duration: '25 phút',
        isPracticalLab: false,
      },
      {
        id: 'syl-2-2',
        title: 'Bài 2: Thực hành 3D - Mạch công tắc đảo chiều kép',
        duration: '45 phút',
        isPracticalLab: true,
        labGoal: 'Lắp ráp hệ thống 2 công tắc điều khiển 1 đèn LED từ 2 vị trí độc lập.',
      },
      {
        id: 'syl-2-3',
        title: 'Bài 3: Cấu tạo & Cuộn hút điện từ của Relay',
        duration: '30 phút',
        isPracticalLab: false,
      },
      {
        id: 'syl-2-4',
        title: 'Bài 4: Thực hành 3D - Mạch rơle tự giữ (Latching Circuit)',
        duration: '50 phút',
        isPracticalLab: true,
        labGoal: 'Thiết kế mạch đóng ngắt nút nhấn Start/Stop với rơle tự duy trì trạng thái.',
      },
    ],
    createLabProject: () => {
      const doc = createDefaultProjectDocument('Thực hành: Mạch chuyển mạch công tắc');
      doc.components = [
        {
          instanceId: 'pwr-1',
          definitionId: 'dc-source',
          name: 'Nguồn 9V',
          position: { x: -50, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { voltage: 9.0 },
        },
        {
          instanceId: 'sw-1',
          definitionId: 'switch',
          name: 'Công tắc SW1',
          position: { x: -15, y: 0, z: -15 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { type: 'slide' },
        },
        {
          instanceId: 'res-1',
          definitionId: 'resistor',
          name: 'R 470Ω',
          position: { x: 20, y: 0, z: -15 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { resistance: 470 },
        },
        {
          instanceId: 'led-1',
          definitionId: 'led',
          name: 'LED Xanh',
          position: { x: 45, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { color: 'green' },
        },
      ];
      return doc;
    },
  },
  {
    id: 'course-digital-logic',
    title: 'Thiết Kế Mạch Logic Số & Cổng Boolean Tương Tác 3D',
    slug: 'mach-logic-so-cong-boolean-3d',
    tagline: 'Xây dựng tư duy logic phần cứng với các cổng AND, OR, NOT, XOR và mạch tổ hợp.',
    description:
      'Khóa học cung cấp nền tảng toán học logic Boolean và cách hiện thực hóa các bảng chân trị (Truth Table) thành các khối mạch thực tế. Bạn sẽ học cách thiết kế bộ cộng nhị phân bán phần, bộ chọn kênh Multiplexer và khóa mã số bí mật.',
    author: {
      id: 'author-le-dang-khoa',
      name: 'TS. Lê Đăng Khoa',
      role: 'Trưởng bộ môn Kỹ thuật Máy tính & Vi mạch số',
    },
    instructor: {
      name: 'TS. Lê Đăng Khoa',
      role: 'Trưởng bộ môn Kỹ thuật Máy tính & Vi mạch số',
    },
    price: 199000,
    currency: 'VND',
    originalPrice: 350000,
    isFree: false,
    level: 'Trung cấp',
    category: 'digital',
    duration: '5.5 giờ',
    lessonCount: 6,
    rating: 4.95,
    reviewsCount: 640,
    studentsCount: 1450,
    thumbnailGradient: 'from-blue-600 via-indigo-600 to-violet-800',
    badge: 'Bán chạy nhất',
    highlights: [
      'Nguyên lý hoạt động các cổng cơ bản AND, OR, NOT, NAND, NOR, XOR',
      'Chuyển đổi bảng chân trị thành sơ đồ nguyên lý mạch điện',
      'Thực hành 3D thiết kế bộ cộng bán phần 2 bit (Half Adder)',
      'Ứng dụng trong mạch mật mã mã pin bảo mật 3 cổng logic',
    ],
    syllabus: [
      {
        id: 'syl-3-1',
        title: 'Bài 1: Đại số logic Boolean & Bảng trạng thái',
        duration: '30 phút',
        isPracticalLab: false,
      },
      {
        id: 'syl-3-2',
        title: 'Bài 2: Thực hành 3D - Cổng AND & OR dùng công tắc nối tiếp / song song',
        duration: '45 phút',
        isPracticalLab: true,
        labGoal: 'Ghép 2 công tắc để minh họa logic AND (cùng đóng) và OR (1 trong 2 đóng).',
      },
      {
        id: 'syl-3-3',
        title: 'Bài 3: Cổng NAND vạn năng & Luật De Morgan',
        duration: '35 phút',
        isPracticalLab: false,
      },
      {
        id: 'syl-3-4',
        title: 'Bài 4: Thực hành 3D - Mạch bảo mật mã khóa số 2 tầng',
        duration: '60 phút',
        isPracticalLab: true,
        labGoal: 'Xây dựng mạch khóa điện tử chỉ kích hoạt khi đúng tổ hợp các công tắc đầu vào.',
      },
    ],
    createLabProject: () => {
      const doc = createDefaultProjectDocument('Thực hành: Mạch Logic AND/OR');
      doc.components = [
        {
          instanceId: 'pwr-1',
          definitionId: 'dc-source',
          name: 'Nguồn 5V',
          position: { x: -60, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { voltage: 5.0 },
        },
        {
          instanceId: 'sw-1',
          definitionId: 'switch',
          name: 'Công tắc Input A',
          position: { x: -30, y: 0, z: -20 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { type: 'slide' },
        },
        {
          instanceId: 'sw-2',
          definitionId: 'switch',
          name: 'Công tắc Input B',
          position: { x: 0, y: 0, z: -20 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { type: 'slide' },
        },
        {
          instanceId: 'res-1',
          definitionId: 'resistor',
          name: 'R 330Ω',
          position: { x: 30, y: 0, z: -20 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { resistance: 330 },
        },
        {
          instanceId: 'led-1',
          definitionId: 'led',
          name: 'LED Ngõ Ra',
          position: { x: 55, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { color: 'blue' },
        },
      ];
      return doc;
    },
  },
  {
    id: 'course-timer-555',
    title: 'Mastering IC Định Thời 555 & Dao Động Xung Đồng Hồ',
    slug: 'mastering-ic-timer-555-mach-dao-dong',
    tagline: 'Khám phá trái tim tạo nhịp của mọi mạch điện tử: IC 555 chế độ Đa hài và Đơn ổn.',
    description:
      'IC 555 là linh kiện kinh điển được bán ra hàng tỷ chiếc. Khóa học hướng dẫn bạn từ nguyên lý so sánh điện áp bên trong (Voltage Comparators) đến việc ghép tụ điện nạp/xả để tạo xung vuông điều khiển đèn nhấp nháy, còi báo cảnh sát và điều chế độ rộng xung PWM.',
    author: {
      id: 'author-vu-minh-quan',
      name: 'Kỹ Sư Vũ Minh Quân',
      role: 'Chuyên gia Thiết kế Bo mạch Nhúng IoT',
    },
    instructor: {
      name: 'Kỹ Sư Vũ Minh Quân',
      role: 'Chuyên gia Thiết kế Bo mạch Nhúng IoT',
    },
    price: 299000,
    currency: 'VND',
    originalPrice: 480000,
    isFree: false,
    level: 'Trung cấp',
    category: 'analog',
    duration: '6.0 giờ',
    lessonCount: 7,
    rating: 4.98,
    reviewsCount: 512,
    studentsCount: 1180,
    thumbnailGradient: 'from-purple-600 via-pink-600 to-rose-600',
    badge: 'Khuyên dùng',
    highlights: [
      'Cấu trúc bên trong IC 555: 3 điện trở 5kΩ, 2 bộ so sánh và Flip-Flop SR',
      'Công thức tính chu kỳ T, tần số f và Duty Cycle của chế độ Astable',
      'Thực hành 3D: Mạch đèn LED cảnh báo giao thông nhấp nháy',
      'Ứng dụng tạo xung PWM điều chỉnh độ sáng đèn mượt mà',
    ],
    syllabus: [
      {
        id: 'syl-4-1',
        title: 'Bài 1: Sơ đồ chân và cấu trúc nội tại của IC 555',
        duration: '35 phút',
        isPracticalLab: false,
      },
      {
        id: 'syl-4-2',
        title: 'Bài 2: Tụ điện RC và đồ thị nạp xả hàm mũ',
        duration: '30 phút',
        isPracticalLab: false,
      },
      {
        id: 'syl-4-3',
        title: 'Bài 3: Thực hành 3D - Lắp ráp mạch đèn chớp tắt nhịp điệu',
        duration: '60 phút',
        isPracticalLab: true,
        labGoal: 'Kết nối mạch dao động đa hài với IC 555 để quan sát LED nháy liên tục.',
      },
      {
        id: 'syl-4-4',
        title: 'Bài 4: Thực hành 3D - Điều chỉnh tần số bằng biến trở',
        duration: '45 phút',
        isPracticalLab: true,
        labGoal: 'Thay đổi giá trị biến trở để tăng giảm tốc độ chớp từ 1Hz đến 20Hz.',
      },
    ],
    createLabProject: () => {
      const doc = createDefaultProjectDocument('Thực hành: Mạch Tạo Dao Động 555');
      doc.components = [
        {
          instanceId: 'pwr-1',
          definitionId: 'dc-source',
          name: 'Nguồn 9V',
          position: { x: -60, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { voltage: 9.0 },
        },
        {
          instanceId: 'ic-1',
          definitionId: 'ic-dip8',
          name: 'NE555 Timer',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: {},
        },
        {
          instanceId: 'res-1',
          definitionId: 'resistor',
          name: 'R1 10kΩ',
          position: { x: -30, y: 0, z: -25 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { resistance: 10000 },
        },
        {
          instanceId: 'led-1',
          definitionId: 'led',
          name: 'LED Xung Ra',
          position: { x: 50, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { color: 'red' },
        },
      ];
      return doc;
    },
  },
  {
    id: 'course-pcb-design-gerber',
    title: 'Thiết Kế Bo Mạch PCB Chuẩn Công Nghiệp & Xuất Gerber',
    slug: 'thiet-ke-pcb-chuan-cong-nghiep-xuat-gerber',
    tagline: 'Quy trình hoàn chỉnh từ sơ đồ nguyên lý đến sản xuất bo mạch thật tại nhà máy.',
    description:
      'Khóa học nâng cao dành cho kỹ sư và sinh viên muốn làm chủ thiết kế bo mạch in (PCB) đa lớp. Hướng dẫn chi tiết bố trí linh kiện giảm nhiễu EMI, phân tách mặt đất GND analog/digital, chạy quy tắc kiểm tra DRC và xuất bộ tệp Gerber RS-274X tiêu chuẩn quốc tế.',
    author: {
      id: 'author-do-gia-huy',
      name: 'KS. Đỗ Gia Huy',
      role: 'Trưởng nhóm Thiết kế Phần cứng tại FPT Semiconductor',
    },
    instructor: {
      name: 'KS. Đỗ Gia Huy',
      role: 'Trưởng nhóm Thiết kế Phần cứng tại FPT Semiconductor',
    },
    price: 590000,
    currency: 'VND',
    originalPrice: 950000,
    isFree: false,
    level: 'Chuyên sâu',
    category: 'pcb',
    duration: '8.5 giờ',
    lessonCount: 9,
    rating: 4.99,
    reviewsCount: 420,
    studentsCount: 890,
    thumbnailGradient: 'from-emerald-600 via-teal-700 to-slate-900',
    badge: 'Chuyên gia',
    highlights: [
      'Bố trí đường mạch tín hiệu cao tần & đổ đồng Ground Plane',
      'Thiết lập khoảng cách cách điện Clearance & độ rộng Track Width',
      'Kiểm định tự động DRC (Design Rule Check) chống ngắn mạch',
      'Xuất Gerber RS-274X, Drill NC và đặt hàng gia công thực tế',
    ],
    syllabus: [
      {
        id: 'syl-5-1',
        title: 'Bài 1: Kiến trúc xếp lớp (Stackup) bo mạch 2 lớp & 4 lớp',
        duration: '40 phút',
        isPracticalLab: false,
      },
      {
        id: 'syl-5-2',
        title: 'Bài 2: Thực hành 3D - Bố trí linh kiện tối ưu diện tích và tản nhiệt',
        duration: '70 phút',
        isPracticalLab: true,
        labGoal: 'Sắp xếp nguồn, IC, tải trên bo mạch 3D và quan sát đường nối netlist.',
      },
      {
        id: 'syl-5-3',
        title: 'Bài 3: Thực hành 3D - Định tuyến vết đồng (Trace Routing) & Vias xuyên tầng',
        duration: '90 phút',
        isPracticalLab: true,
        labGoal: 'Vẽ các đường mạch dây đồng đảm bảo góc bo 45 độ và không tạo antenna gây nhiễu.',
      },
      {
        id: 'syl-5-4',
        title: 'Bài 4: Xuất Gerber RS-274X & Kiểm tra tệp chế tạo với CAM Viewer',
        duration: '50 phút',
        isPracticalLab: false,
      },
    ],
    createLabProject: () => {
      const doc = createDefaultProjectDocument('Thực hành: Thiết Kế Bo Mạch PCB');
      doc.board = {
        width: 100,
        depth: 70,
        thickness: 1.6,
        copperLayerCount: 2,
        gridSpacing: 2.54,
        solderMaskColor: '#0f4c3a',
      };
      doc.components = [
        {
          instanceId: 'pwr-1',
          definitionId: 'dc-source',
          name: 'Khối Nguồn 12V',
          position: { x: -35, y: 0, z: -20 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { voltage: 12.0 },
        },
        {
          instanceId: 'ic-1',
          definitionId: 'ic-dip8',
          name: 'IC Vi Điều Khiển',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: {},
        },
        {
          instanceId: 'led-1',
          definitionId: 'led',
          name: 'LED Báo Nguồn',
          position: { x: 35, y: 0, z: 20 },
          rotation: { x: 0, y: 0, z: 0 },
          parameters: { color: 'green' },
        },
      ];
      return doc;
    },
  },
];
